"""Mission round-close report — the authoritative participation ledger.

Generated by ``HFLHostMission`` (mission-scope), consumed in-flight by
``FLScheduler`` (fast-phase Deadline update) and shipped at dock by
``ClientCluster`` to ``HFLHostCluster`` (slow-phase reconciliation).

Phase 1 only needs the data shapes — the writer lives in Phase 2.

Design refs:
* HERMES_FL_Scheduler_Design.md §6.3 HFLHostMission state
* HERMES_FL_Scheduler_Design.md §4 step (12)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Tuple

from .ids import DeviceID, MuleID


class MissionOutcome(str, Enum):
    """Per-device outcome of one in-mission FL session."""

    CLEAN = "clean"  # gradient verified, merged into partial aggregate
    PARTIAL = "partial"  # gradient arrived but failed verification
    TIMEOUT = "timeout"  # device never responded / TTL expired

    def is_on_time(self) -> bool:
        return self is MissionOutcome.CLEAN


class DeliveryOutcome(str, Enum):
    """Per-device outcome of one Pass-2 delivery attempt.

    Sprint 1.5 design §7 principle 13: every Pass-2 contact must reach
    every reachable device, otherwise the un-reached device spends the
    next mission training against a stale θ. The cluster ingests this
    enum to decide whether to bump ``DeviceRecord.delivery_priority``.
    """

    DELIVERED = "delivered"  # device acknowledged θ' receipt
    UNDELIVERED = "undelivered"  # device did not acknowledge in TTL

    def is_delivered(self) -> bool:
        return self is DeliveryOutcome.DELIVERED


@dataclass(frozen=True)
class MissionRoundCloseLine:
    """One device's row in the mission round-close report."""

    device_id: DeviceID
    outcome: MissionOutcome
    contact_ts: float  # epoch seconds when contact was made
    bytes_received: int = 0
    bytes_sent: int = 0


@dataclass
class MissionRoundCloseReport:
    """Authoritative participation ledger for one mission slice."""

    mule_id: MuleID
    mission_round: int
    started_at: float
    finished_at: float
    lines: List[MissionRoundCloseLine] = field(default_factory=list)

    def append(self, line: MissionRoundCloseLine) -> None:
        self.lines.append(line)

    # convenience aggregates used by HFLHostCluster reconciliation
    def participants(self) -> List[DeviceID]:
        return [l.device_id for l in self.lines if l.outcome.is_on_time()]

    def missed(self) -> List[DeviceID]:
        return [l.device_id for l in self.lines if not l.outcome.is_on_time()]

    def counts(self) -> Tuple[int, int]:
        """``(on_time, missed)`` — handy for cluster summary metrics."""
        on_time = sum(1 for l in self.lines if l.outcome.is_on_time())
        return on_time, len(self.lines) - on_time


@dataclass(frozen=True)
class ContactRecord:
    """One contact event during a mission — superset of round-close lines.

    Includes opportunistic beacons that did not result in an FL session, so
    the cluster sees beacon coverage even when no gradient was collected.
    """

    device_id: DeviceID
    contact_ts: float
    in_session: bool  # True if a full FL session ran
    snr_at_contact: float = 0.0


@dataclass
class ContactHistory:
    """All contact events from one mission, ordered by ``contact_ts``."""

    mule_id: MuleID
    mission_round: int
    records: List[ContactRecord] = field(default_factory=list)

    def add(self, rec: ContactRecord) -> None:
        self.records.append(rec)


@dataclass(frozen=True)
class MissionDeliveryLine:
    """One device's row in the Pass-2 delivery ledger."""

    device_id: DeviceID
    outcome: DeliveryOutcome
    contact_ts: float


@dataclass
class MissionDeliveryReport:
    """Pass-2 ledger — emitted by ``HFLHostMission`` after Pass 2 closes.

    Companion to :class:`MissionRoundCloseReport` (Pass 1's ledger). The
    cluster uses this to bump ``DeviceRecord.delivery_priority`` for any
    UNDELIVERED row, and to reset it on a DELIVERED row.

    Design refs:
    * HERMES_FL_Scheduler_Design.md §6.3 (HFLHostMission state)
    * HERMES_FL_Scheduler_Design.md §4 step (27)
    * HERMES_FL_Scheduler_Implementation_Plan.md §3.6.2 task 9
    """

    mule_id: MuleID
    mission_round: int
    started_at: float
    finished_at: float
    lines: List[MissionDeliveryLine] = field(default_factory=list)

    def append(self, line: MissionDeliveryLine) -> None:
        self.lines.append(line)

    def delivered(self) -> List[DeviceID]:
        return [l.device_id for l in self.lines if l.outcome.is_delivered()]

    def undelivered(self) -> List[DeviceID]:
        return [l.device_id for l in self.lines if not l.outcome.is_delivered()]

    def counts(self) -> Tuple[int, int]:
        """``(delivered, undelivered)`` — for the cluster's summary metric."""
        delivered = sum(1 for l in self.lines if l.outcome.is_delivered())
        return delivered, len(self.lines) - delivered
