"""Mission round-close report — the authoritative participation ledger.

Generated by ``HFLHostMission`` (mission-scope), consumed in-flight by
``FLScheduler`` (fast-phase Deadline update) and shipped at dock by
``ClientCluster`` to ``HFLHostCluster`` (slow-phase reconciliation).

Phase 1 only needs the data shapes — the writer lives in Phase 2.

Design refs:
* HERMES_FL_Scheduler_Design.md §6.3 HFLHostMission state
* HERMES_FL_Scheduler_Design.md §4 step (12)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional, Tuple

from .ids import DeviceID, MuleID


class MissionOutcome(str, Enum):
    """Per-device outcome of one in-mission FL session."""

    CLEAN = "clean"  # gradient verified, merged into partial aggregate
    PARTIAL = "partial"  # gradient arrived but failed verification
    TIMEOUT = "timeout"  # device never responded / TTL expired

    def is_on_time(self) -> bool:
        return self is MissionOutcome.CLEAN


class DeliveryOutcome(str, Enum):
    """Per-device outcome of one Pass-2 delivery attempt.

    Sprint 1.5 design §7 principle 13: every Pass-2 contact must reach
    every reachable device, otherwise the un-reached device spends the
    next mission training against a stale θ. The cluster ingests this
    enum to decide whether to bump ``DeviceRecord.delivery_priority``.
    """

    DELIVERED = "delivered"  # device acknowledged θ' receipt
    UNDELIVERED = "undelivered"  # device did not acknowledge in TTL
    # Budgeted Pass 2 (FeRRy Phase 1) did not fly to this device: it keeps its
    # older basis. Counts as not delivered wherever delivery is tallied.
    SKIPPED = "skipped"

    def is_delivered(self) -> bool:
        return self is DeliveryOutcome.DELIVERED


@dataclass(frozen=True)
class MissionRoundCloseLine:
    """One device's row in the mission round-close report.

    ``basis_version`` and ``age`` describe the update a CLEAN session
    collected: the version of the θ it was trained from, and how many cluster
    rounds older that is than the θ the mule carried. ``band`` is the contact
    band once the contact link has one (FeRRy Phase 3); None until then.

    FeRRy Phase 3: on the mission clock, ``contact_ts`` is simulated seconds
    (the contact's arrival plus the airtime committed before this session
    ended), and ``band`` is the band class index (``hermes.l1.contact_link
    .CLASSES``: 0 wide, 1 medium, 2 narrow) with ``snr_db`` the contact SNR
    the session was priced at: at the session's own start for a device that
    answered, at arrival for one that did not (design section 4.3). Both stay
    None on the wall clock and on the mission clock without a band.
    """

    device_id: DeviceID
    outcome: MissionOutcome
    contact_ts: float  # epoch seconds when contact was made
    bytes_received: int = 0
    bytes_sent: int = 0
    num_examples: int = 0
    basis_version: Optional[int] = None
    age: Optional[int] = None
    band: Optional[int] = None
    snr_db: Optional[float] = None


@dataclass
class MissionRoundCloseReport:
    """Authoritative participation ledger for one mission slice."""

    mule_id: MuleID
    mission_round: int
    started_at: float
    finished_at: float
    lines: List[MissionRoundCloseLine] = field(default_factory=list)

    def append(self, line: MissionRoundCloseLine) -> None:
        self.lines.append(line)

    # convenience aggregates used by HFLHostCluster reconciliation
    def participants(self) -> List[DeviceID]:
        return [l.device_id for l in self.lines if l.outcome.is_on_time()]

    def missed(self) -> List[DeviceID]:
        return [l.device_id for l in self.lines if not l.outcome.is_on_time()]

    def counts(self) -> Tuple[int, int]:
        """``(on_time, missed)`` — handy for cluster summary metrics."""
        on_time = sum(1 for l in self.lines if l.outcome.is_on_time())
        return on_time, len(self.lines) - on_time


@dataclass(frozen=True)
class ContactRecord:
    """One contact event during a mission — superset of round-close lines.

    Includes opportunistic beacons that did not result in an FL session, so
    the cluster sees beacon coverage even when no gradient was collected.

    FeRRy Phase 3: the ferry path stamps ``contact_ts`` from the mission clock
    (never the device's advert time) and fills ``snr_at_contact`` with the
    line's ``snr_db`` when the contact has a band; 0.0 otherwise, as before.
    """

    device_id: DeviceID
    contact_ts: float
    in_session: bool  # True if a full FL session ran
    snr_at_contact: float = 0.0


@dataclass
class ContactHistory:
    """All contact events from one mission, ordered by ``contact_ts``."""

    mule_id: MuleID
    mission_round: int
    records: List[ContactRecord] = field(default_factory=list)

    def add(self, rec: ContactRecord) -> None:
        self.records.append(rec)


@dataclass(frozen=True)
class MissionDeliveryLine:
    """One device's row in the Pass-2 delivery ledger.

    FeRRy Phase 3: ``band`` is the contact band class index (as on
    :class:`MissionRoundCloseLine`; None without a band) and ``bytes_sent`` the
    bytes of θ' pushed to the device, 0 when no push went out. Only the ferry
    path fills them; ``contact_ts`` is then simulated seconds.
    """

    device_id: DeviceID
    outcome: DeliveryOutcome
    contact_ts: float
    band: Optional[int] = None
    bytes_sent: int = 0


@dataclass
class MissionDeliveryReport:
    """Pass-2 ledger — emitted by ``HFLHostMission`` after Pass 2 closes.

    Companion to :class:`MissionRoundCloseReport` (Pass 1's ledger). The
    cluster uses this to bump ``DeviceRecord.delivery_priority`` for any
    UNDELIVERED row, and to reset it on a DELIVERED row.

    Design refs:
    * HERMES_FL_Scheduler_Design.md §6.3 (HFLHostMission state)
    * HERMES_FL_Scheduler_Design.md §4 step (27)
    * HERMES_FL_Scheduler_Implementation_Plan.md §3.6.2 task 9
    """

    mule_id: MuleID
    mission_round: int
    started_at: float
    finished_at: float
    lines: List[MissionDeliveryLine] = field(default_factory=list)

    def append(self, line: MissionDeliveryLine) -> None:
        self.lines.append(line)

    def delivered(self) -> List[DeviceID]:
        return [l.device_id for l in self.lines if l.outcome.is_delivered()]

    def undelivered(self) -> List[DeviceID]:
        return [l.device_id for l in self.lines if not l.outcome.is_delivered()]

    def counts(self) -> Tuple[int, int]:
        """``(delivered, undelivered)`` — for the cluster's summary metric."""
        delivered = sum(1 for l in self.lines if l.outcome.is_delivered())
        return delivered, len(self.lines) - delivered
